---
- name: Include OS specific vars
  ansible.builtin.include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_facts['os_family'] }}-{{ ansible_facts['distribution'] }}-{{ ansible_facts['distribution_major_version'] }}.yml"
        - "{{ ansible_facts['os_family'] }}-{{ ansible_facts['distribution_major_version'] }}.yml"
        - "{{ ansible_facts['os_family'] }}-{{ ansible_facts['distribution'] }}.yml"
        - "{{ ansible_facts['os_family'] }}-{{ ansible_facts['lsb']['id'] if ansible_facts['lsb']['id'] is defined else ansible_facts['distribution'] }}.yml"
        - "{{ ansible_facts['os_family'] }}.yml"
        - default.yml
      paths:
        - "{{ role_path }}/vars"

- name: Include OS specific vars regarding Icinga subscription
  ansible.builtin.include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "subscription-{{ ansible_facts['os_family'] }}-{{ ansible_facts['distribution'] }}-{{ ansible_facts['distribution_major_version'] }}.yml"
        - "subscription-{{ ansible_facts['os_family'] }}-{{ ansible_facts['distribution_major_version'] }}.yml"
        - "subscription-{{ ansible_facts['os_family'] }}-{{ ansible_facts['distribution'] }}.yml"
        - "subscription-{{ ansible_facts['os_family'] }}.yml"
        - default.yml
      paths:
        - "{{ role_path }}/vars"
  when:
    - icinga_repo_subscription_username is defined
    - icinga_repo_subscription_password is defined

- name: Check OS family
  vars:
    _paths: "{{ ansible_search_path }}"
    _file: "{{ ansible_facts['os_family'] }}.yml"
    _tasks_file: "{{ lookup('first_found', paths=_paths, files=_file, skip=true) }}"
  block:
    - name: Add repositories {{ ansible_facts['os_family'] }}
      when: _tasks_file | length > 0
      ansible.builtin.include_tasks: "{{ ansible_facts['os_family'] }}.yml"

    - name: "OS family not supported!"
      when: _tasks_file | length == 0
      ansible.builtin.fail:
        msg: "The OS '{{ ansible_facts['os_family'] }}' is not supported!"
