---
- name: Include OS specific vars
  ansible.builtin.include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_facts['os_family'] | lower }}-{{ ansible_facts['distribution'] | lower }}-{{ ansible_facts['distribution_major_version'] | lower }}.yml"
        - "{{ ansible_facts['os_family'] | lower }}-{{ ansible_facts['distribution_major_version'] | lower }}.yml"
        - "{{ ansible_facts['os_family'] | lower }}-{{ ansible_facts['distribution'] | lower }}.yml"
        - "{{ ansible_facts['os_family'] | lower }}.yml"
        - default.yml
      paths:
        - "{{ role_path }}/vars"

- name: Check each icingaweb2_modules key against known modules
  when: not icingaweb2_ignore_unknown_modules
  loop: "{{ icingaweb2_modules | default({}) | dict2items }}"
  loop_control:
    label: "{{ item.key }}"
  ansible.builtin.assert:
    that:
      - item.key in icingaweb2_module_packages.keys()
    fail_msg: "'{{ item.key }}' is an unknown module. Set 'icingaweb2_ignore_unknown_modules' to 'true' if you want to simply skip unknown modules"

- name: Gather module packages
  ansible.builtin.set_fact:
    icingaweb2_packages: "{{ icingaweb2_packages + [ icingaweb2_module_packages[item.key] ] }}"
  loop: "{{ icingaweb2_modules | dict2items }}"
  loop_control:
    label: "{{ item.key }}"
  when:
    - icingaweb2_modules is defined
    - icingaweb2_module_packages[item.key] is defined
    - item.value.source == "package"
  no_log: true

- name: Check supported operatingsystems
  vars:
    _paths: "{{ ansible_search_path }}"
    _file: "install_on_{{ ansible_facts['os_family'] | lower }}.yml"
    _tasks_file: "{{ lookup('first_found', paths=_paths, files=_file, skip=true) }}"
  block:
    - name: Include OS specific installation
      when: _tasks_file | length > 0
      ansible.builtin.include_tasks: "install_on_{{ ansible_facts['os_family'] | lower }}.yml"

    - name: "OS family not supported!"
      when: _tasks_file | length == 0
      ansible.builtin.fail:
        msg: "The OS '{{ ansible_facts['os_family'] }}' is not supported!"

- name: Manage Icinga Web 2 config
  ansible.builtin.include_tasks: "manage_icingaweb_config.yml"

- name: Manage Icinga Web 2 DB
  ansible.builtin.include_tasks: "manage_icingaweb_db.yml"
  when:
    - icingaweb2_db is defined
    - (icingaweb2_db_import_schema | default(false)) or (icingaweb2_users is defined) or (icingaweb2_admin_username is defined)

- name: Manage module states
  ansible.builtin.file:
    src: "{{ icingaweb2_config.global.module_path + '/' + item.key if item.value.enabled|bool == true else omit }}"
    dest: "{{ icingaweb2_config_dir }}/enabledModules/{{ item.key }}"
    owner: "{{ icingaweb2_httpd_user }}"
    group: "{{ icingaweb2_group }}"
    state: "{{ 'link' if item.value.enabled|bool == true else 'absent' }}"
    force: yes
  when:
    - icingaweb2_modules is defined
    - item.key in icingaweb2_module_packages.keys()
  loop: "{{ icingaweb2_modules | dict2items }}"
  loop_control:
    label: "Ensure {{ item.key }} is {{ 'enabled' if item.value.enabled|default(false)|bool == true else 'disabled' }}"

- name: Configure modules
  ansible.builtin.include_tasks: "modules/{{ item.key }}.yml"
  when:
    - icingaweb2_modules is defined
    - item.key in icingaweb2_module_packages.keys()
  loop: "{{ icingaweb2_modules | dict2items }}"
  loop_control:
    label: "{{ item.key }}"

# Many daemons fail before e.g. the resource is set up or the schema hasn't been migrated. This is a workaround.
- name: Manage enabled module daemons
  ansible.builtin.service:
    name: "icinga-{{ item.key }}"
    state: restarted
  when: icingaweb2_modules is defined and item.value.enabled|default(false)|bool == true and item.key in ['vspheredb', 'x509']
  loop: "{{ icingaweb2_modules | dict2items }}"
  loop_control:
    label: "{{ item.key }}"
